### ISSUE TITLE
Divide by Zero error and a Question

### ISSUE THREAD

**Issue by pacas00** [Nogg-aholic/NogsResearch#1]
<- Idiot hit enter by accident, editing.

Greetings, I attempted to try out this mod today and noticed that there is an error. The following is spammed in logs.

`[2020.10.19-12.30.09:933][388]LogScript: Warning: Script Msg: Divide by zero detected: 8.000000 / 0
Script call stack:
	Function /Game/NogsResearch/ResearchUI/Widget_ResearchUI.Widget_ResearchUI_C:PercentDoneOrInQue`

Nothing appears on the right hand side of the UI (though i don't quite know how this works, so i could just be doing it wrong)

![IngameUI](https://user-images.githubusercontent.com/566033/96452556-873ac900-125c-11eb-8f3e-ba9bbe640eba.png)

I've tried with and without items in the manager inventory on the bottom left, and with and without items in one or multiple researchers.

[SatisfactoryModLoader.log](https://github.com/Nogg-aholic/NogsResearch/files/5401794/SatisfactoryModLoader.log)
[FactoryGame.log](https://github.com/Nogg-aholic/NogsResearch/files/5401796/FactoryGame.log)
pre-launch-debug not included as it contains no errors.

Please let me know if I'm just stupid (well, more so than hitting enter early) or if you need more info.

**Comment by Nogg-aholic** [comment]
Hey pacas00, 
thanks for the Bug-Report. This Issue will be resolved with the next Update. For now saving and reloading the Game will take care of the empty UI and most likely the divided by Zero logs. 
to explain : The Research System currently fails to Init itself on Spawn, however when its loaded in via a saved Object, it will run the Init Function causing it to work again.

**Comment by alronefisher** [comment]
I'd like to say that I love the mod and you have done great work on it. No rush or anything I know you have more important things to do, But is there any kind of ETA on this fix? It makes multiplayer almost unusable and I really like it.
