### ISSUE TITLE
Crash in Early Acces and barey visible ui in Experimental

### ISSUE THREAD

**Issue by Boesergolf** [Nogg-aholic/NogsResearch#2]
Hey have 2 Problems with your mods ,
If i use It in the Base Game the ui is fine but it crashes my Game as soon as i try to connect the Researcher with Power.

If i use it in Experimental the above issue is not there but the Research ui is barely visible.

![grafik](https://user-images.githubusercontent.com/47137382/98438672-229cbc80-20ec-11eb-9651-397bd490701f.png)
![grafik](https://user-images.githubusercontent.com/47137382/98438697-3516f600-20ec-11eb-89f0-fe169a61277b.png)

**Comment by Nogg-aholic** [comment]
Hey ,the problem appears to be UI Scaling here ,i will try to put the Small Elements ( Text on the Left as well as Inventory ) in a ScaleBox adjusting upwards if needed. That should fix the Issue. The Reason for the Crash with the Non-Experimental version, i would assume has to do with the Update on EX. The Version before should work^tm.

**Comment by Boesergolf** [comment]
thank you

**Comment by budak7273** [comment]
Closed because the issue seems to have been fixed, and this HUD no longer exists in the U5/6 versions of the mod
