### ISSUE TITLE
Game Crashing when Disassembling Researcher

### ISSUE THREAD

**Issue by lancce-Wolf** [Nogg-aholic/NogsResearch#3]
every now and then my game crashes when i disassemble a researcher. i dont really know why that is but i noticed it happens more often when the research controller has something qued in or if a researcher has items left in it. if my game crashes again i'll try to send the crash log. (am playing with 50+ mods just for your information)

**Comment by Nogg-aholic** [comment]
Hey, Thanks for the Bug Report ! 
A crash log would really help to find the Source here.  But i think i know what the issue is , and i will try to fix it with the next Version provided i can reproduce the crash.

**Comment by lancce-Wolf** [comment]
it doesnt happen as much as it did before but it mostly happens for me when ever i disassembled something while there was something selected in the research controller.
