### ISSUE TITLE
Hard Drive scan not working

### ISSUE THREAD

**Issue by zmooth86** [Nogg-aholic/NogsResearch#4]
This mod is awesome, because it makes research so much more interesting and convenient at the same time. Thank you for the good work. Sadly no matter what I try, unlock alternate recipes does not seem to work. I put hard drive in every inventory, but nothing happens.  
One thing I noticed, is a negative completion time in the tooltip
![image](https://user-images.githubusercontent.com/13665055/112331774-84d01580-8cb9-11eb-8cf7-055402a0e534.png)
Maybe thats part of the problem?

Would be awesome to be able to queue the scans and just let it work.

**Comment by budak7273** [comment]
Closing because this feature is no longer a part of Nog's Research as of the U5/6 versions of the mod
