### ISSUE TITLE
entire left menu disappears with extended inventory

### ISSUE THREAD

**Issue by cpjet64** [Nogg-aholic/NogsResearch#5]
when i open the research machine it starts out like this
![image](https://user-images.githubusercontent.com/38527447/120079490-0d847c80-c082-11eb-8f7c-2f9b00d71f28.png)

 and then in about 1 second it changes to this 
![image](https://user-images.githubusercontent.com/38527447/120079472-e9c13680-c081-11eb-9a4e-24ffca3bee7c.png)

i think its because your mod is autoresizing the player inventory display

**Comment by budak7273** [comment]
Closing because this UI is no longer a part of Nog's Research as of the U5/6 versions of the mod
